# Author : Maxime Escourbiac <maxime.escourbiac@michelin.com>
# Last update : 2023-09-11
version: '3'

services:

  crypto_ticketgen:
    image: fisjkars/ticketgen:3.0.0
    ports:
      - "30000:8080"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 600M

  crypto_waterboard:
    image: fisjkars/waterboard:3.0.0
    ports:
      - "30001:8080"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 600M

  reverse_really:
    image: fisjkars/really:3.0.0
    ports:
      - "25001:1337"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 200M

  reverse_storyteller:
    image: fisjkars/storyteller:3.0.0
    ports:
      - "25002:1337"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 200M

  web_matrix:
    image: fisjkars/matrix:3.0.0
    ports:
      - "40001:8080"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 200M

  web_whatthephp:
    image: fisjkars/whatthephp:3.0.0
    ports:
      - "40002:8080"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 200M

  web_idormeifyoucan:
    image: fisjkars/idormeifyoucan2:3.0.0
    ports:
      - "40003:8000"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 200M

  web_holygrail:
    image: fisjkars/holygrail:3.0.0
    ports:
      - "40004:8080"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 200M

  # web_youshallnotpass:
  #   image: youshallnotpass:2.0.0
  #   ports:
  #     - "40007:8080"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.3'
  #         memory: 200M

  # web_youshallnotpassagain:
  #   image: youshallnotpassagain:2.0.0
  #   ports:
  #     - "40008:8080"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.3'
  #         memory: 200M

  # web_clicker:
  #   image: clicker:2.0.0
  #   ports:
  #     - "40009:8080"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.3'
  #         memory: 200M

  # web_moviedb:
  #   image: moviedb:2.0.0
  #   ports:
  #     - "40010:5000"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '1.0'
  #         memory: 400M

  # web_websiterenderer:
  #   image: websiterenderer:2.0.0
  #   ports:
  #     - "40011:5000"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '1.0'
  #         memory: 400M

  # web_whatthephp2:
  #   image: whatthephp2:2.0.0
  #   ports:
  #     - "40012:8080"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.3'
  #         memory: 200M

  # web_theguesser:
  #   image: guesser:2.0.0
  #   ports:
  #     - "40013:8080"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.50'
  #         memory: 600M

  # web_springbootapi:
  #   image: springbootapi:2.0.0
  #   ports:
  #     - "40014:8080"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.3'
  #         memory: 400M

  # web_canyouguessthehash:
  #   image: canyouguessthehash:2.0.0
  #   ports:
  #     - "40015:8080"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.3'
  #         memory: 200M

  # web_dihydrogen:
  #   image: dihydrogen:2.0.0
  #   ports:
  #     - "40016:8080"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.4'
  #         memory: 200M

  # web_holygrail2:
  #   image: holygrailv2:2.0.0
  #   ports:
  #     - "40017:8080"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.3'
  #         memory: 200M

  # web_breakauth:
  #   image: breakauth:2.0.0
  #   ports:
  #     - "40018:8080"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.3'
  #         memory: 200M

  # web_logger:
  #   image: logger:2.0.0
  #   ports:
  #     - "40019:8080"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.5'
  #         memory: 500M

  # web_rickandmorty:
  #   image: rickandmorty:2.0.0
  #   ports:
  #     - "40020:8000"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.3'
  #         memory: 300M

  # web_springbootactuator:
  #   image: sbstarterpack:2.0.0
  #   ports:
  #     - "40021:8080"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.8'
  #         memory: 1200M

  # web_graviteelike:
  #   image: graviteelike:2.0.0
  #   ports:
  #     - "40022:8080"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.5'
  #         memory: 600M

  # web_ssofantome:
  #   image: ssofantome:2.0.0
  #   ports:
  #     - "40023:8080"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.5'
  #         memory: 500M

  # web_tomcatmylover:
  #   image: tomcatmylover:2.0.0
  #   ports:
  #     - "40024:8080"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.3'
  #         memory: 600M

  # web_websiterenderer2:
  #   image: websiterenderer2:2.0.0
  #   ports:
  #     - "40025:5000"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '1.0'
  #         memory: 400M

  # web_dihydrogen2:
  #   image: dihydrogen2:2.0.0
  #   ports:
  #     - "40026:8080"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.5'
  #         memory: 300M
  